
package Replicas.Replica2.com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MasterServerImplService", targetNamespace = "http://example.com/master", wsdlLocation = "http://localhost:8080/masterservice?wsdl")
public class MasterServerImplService
    extends Service
{

    private final static URL MASTERSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MASTERSERVERIMPLSERVICE_EXCEPTION;
    private final static QName MASTERSERVERIMPLSERVICE_QNAME = new QName("http://example.com/master", "MasterServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/masterservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MASTERSERVERIMPLSERVICE_WSDL_LOCATION = url;
        MASTERSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public MasterServerImplService() {
        super(__getWsdlLocation(), MASTERSERVERIMPLSERVICE_QNAME);
    }

    public MasterServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MASTERSERVERIMPLSERVICE_QNAME, features);
    }

    public MasterServerImplService(URL wsdlLocation) {
        super(wsdlLocation, MASTERSERVERIMPLSERVICE_QNAME);
    }

    public MasterServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MASTERSERVERIMPLSERVICE_QNAME, features);
    }

    public MasterServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MasterServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MasterServerImpl
     */
    @WebEndpoint(name = "MasterServerImplPort")
    public MasterServerImpl getMasterServerImplPort() {
        return super.getPort(new QName("http://example.com/master", "MasterServerImplPort"), MasterServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MasterServerImpl
     */
    @WebEndpoint(name = "MasterServerImplPort")
    public MasterServerImpl getMasterServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/master", "MasterServerImplPort"), MasterServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MASTERSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw MASTERSERVERIMPLSERVICE_EXCEPTION;
        }
        return MASTERSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
