
package Replicas.Replica2.com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OUTServerImplService", targetNamespace = "http://example.com/out", wsdlLocation = "http://localhost:8080/OUTServer?wsdl")
public class OUTServerImplService
    extends Service
{

    private final static URL OUTSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OUTSERVERIMPLSERVICE_EXCEPTION;
    private final static QName OUTSERVERIMPLSERVICE_QNAME = new QName("http://example.com/out", "OUTServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OUTServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OUTSERVERIMPLSERVICE_WSDL_LOCATION = url;
        OUTSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public OUTServerImplService() {
        super(__getWsdlLocation(), OUTSERVERIMPLSERVICE_QNAME);
    }

    public OUTServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OUTSERVERIMPLSERVICE_QNAME, features);
    }

    public OUTServerImplService(URL wsdlLocation) {
        super(wsdlLocation, OUTSERVERIMPLSERVICE_QNAME);
    }

    public OUTServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OUTSERVERIMPLSERVICE_QNAME, features);
    }

    public OUTServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OUTServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OUTServerImpl
     */
    @WebEndpoint(name = "OUTServerImplPort")
    public OUTServerImpl getOUTServerImplPort() {
        return super.getPort(new QName("http://example.com/out", "OUTServerImplPort"), OUTServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OUTServerImpl
     */
    @WebEndpoint(name = "OUTServerImplPort")
    public OUTServerImpl getOUTServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/out", "OUTServerImplPort"), OUTServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OUTSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw OUTSERVERIMPLSERVICE_EXCEPTION;
        }
        return OUTSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
