
package Replicas.Replica2.com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VERServerImplService", targetNamespace = "http://example.com/ver", wsdlLocation = "http://localhost:8080/VERServer?wsdl")
public class VERServerImplService
    extends Service
{

    private final static URL VERSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VERSERVERIMPLSERVICE_EXCEPTION;
    private final static QName VERSERVERIMPLSERVICE_QNAME = new QName("http://example.com/ver", "VERServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/VERServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERSERVERIMPLSERVICE_WSDL_LOCATION = url;
        VERSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public VERServerImplService() {
        super(__getWsdlLocation(), VERSERVERIMPLSERVICE_QNAME);
    }

    public VERServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERSERVERIMPLSERVICE_QNAME, features);
    }

    public VERServerImplService(URL wsdlLocation) {
        super(wsdlLocation, VERSERVERIMPLSERVICE_QNAME);
    }

    public VERServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERSERVERIMPLSERVICE_QNAME, features);
    }

    public VERServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VERServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VERServerImpl
     */
    @WebEndpoint(name = "VERServerImplPort")
    public VERServerImpl getVERServerImplPort() {
        return super.getPort(new QName("http://example.com/ver", "VERServerImplPort"), VERServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VERServerImpl
     */
    @WebEndpoint(name = "VERServerImplPort")
    public VERServerImpl getVERServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/ver", "VERServerImplPort"), VERServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw VERSERVERIMPLSERVICE_EXCEPTION;
        }
        return VERSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
