
package com.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ATWImpl", targetNamespace = "http://example.com/atw")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ATWImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeMovieSlotsATW", targetNamespace = "http://example.com/atw", className = "com.example.client.RemoveMovieSlotsATW")
    @ResponseWrapper(localName = "removeMovieSlotsATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.RemoveMovieSlotsATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/removeMovieSlotsATWRequest", output = "http://example.com/atw/ATWImpl/removeMovieSlotsATWResponse")
    public String removeMovieSlotsATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookMovieTicketsATW", targetNamespace = "http://example.com/atw", className = "com.example.client.BookMovieTicketsATW")
    @ResponseWrapper(localName = "bookMovieTicketsATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.BookMovieTicketsATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/bookMovieTicketsATWRequest", output = "http://example.com/atw/ATWImpl/bookMovieTicketsATWResponse")
    public String bookMovieTicketsATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingScheduleATW", targetNamespace = "http://example.com/atw", className = "com.example.client.GetBookingScheduleATW")
    @ResponseWrapper(localName = "getBookingScheduleATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.GetBookingScheduleATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/getBookingScheduleATWRequest", output = "http://example.com/atw/ATWImpl/getBookingScheduleATWResponse")
    public String getBookingScheduleATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMovieShowsAvailabilityATW", targetNamespace = "http://example.com/atw", className = "com.example.client.ListMovieShowsAvailabilityATW")
    @ResponseWrapper(localName = "listMovieShowsAvailabilityATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.ListMovieShowsAvailabilityATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/listMovieShowsAvailabilityATWRequest", output = "http://example.com/atw/ATWImpl/listMovieShowsAvailabilityATWResponse")
    public String listMovieShowsAvailabilityATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelMovieTicketsATW", targetNamespace = "http://example.com/atw", className = "com.example.client.CancelMovieTicketsATW")
    @ResponseWrapper(localName = "cancelMovieTicketsATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.CancelMovieTicketsATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/cancelMovieTicketsATWRequest", output = "http://example.com/atw/ATWImpl/cancelMovieTicketsATWResponse")
    public String cancelMovieTicketsATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovieSlotsATW", targetNamespace = "http://example.com/atw", className = "com.example.client.AddMovieSlotsATW")
    @ResponseWrapper(localName = "addMovieSlotsATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.AddMovieSlotsATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/addMovieSlotsATWRequest", output = "http://example.com/atw/ATWImpl/addMovieSlotsATWResponse")
    public String addMovieSlotsATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "logATW", targetNamespace = "http://example.com/atw", className = "com.example.client.LogATW")
    @ResponseWrapper(localName = "logATWResponse", targetNamespace = "http://example.com/atw", className = "com.example.client.LogATWResponse")
    @Action(input = "http://example.com/atw/ATWImpl/logATWRequest", output = "http://example.com/atw/ATWImpl/logATWResponse")
    public void logATW(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

}
