
package com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ATWImplService", targetNamespace = "http://example.com/atw", wsdlLocation = "http://localhost:8081/atw?wsdl")
public class ATWImplService
    extends Service
{

    private final static URL ATWIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATWIMPLSERVICE_EXCEPTION;
    private final static QName ATWIMPLSERVICE_QNAME = new QName("http://example.com/atw", "ATWImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/atw?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATWIMPLSERVICE_WSDL_LOCATION = url;
        ATWIMPLSERVICE_EXCEPTION = e;
    }

    public ATWImplService() {
        super(__getWsdlLocation(), ATWIMPLSERVICE_QNAME);
    }

    public ATWImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATWIMPLSERVICE_QNAME, features);
    }

    public ATWImplService(URL wsdlLocation) {
        super(wsdlLocation, ATWIMPLSERVICE_QNAME);
    }

    public ATWImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATWIMPLSERVICE_QNAME, features);
    }

    public ATWImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ATWImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ATWImpl
     */
    @WebEndpoint(name = "ATWImplPort")
    public ATWImpl getATWImplPort() {
        return super.getPort(new QName("http://example.com/atw", "ATWImplPort"), ATWImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ATWImpl
     */
    @WebEndpoint(name = "ATWImplPort")
    public ATWImpl getATWImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/atw", "ATWImplPort"), ATWImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATWIMPLSERVICE_EXCEPTION!= null) {
            throw ATWIMPLSERVICE_EXCEPTION;
        }
        return ATWIMPLSERVICE_WSDL_LOCATION;
    }

}
