
package com.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MainServerImpl", targetNamespace = "http://example.com/mainserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MainServerImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeMovieSlots", targetNamespace = "http://example.com/mainserver", className = "com.example.client.RemoveMovieSlots")
    @ResponseWrapper(localName = "removeMovieSlotsResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.RemoveMovieSlotsResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/removeMovieSlotsRequest", output = "http://example.com/mainserver/MainServerImpl/removeMovieSlotsResponse")
    public String removeMovieSlots(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelMovieTickets", targetNamespace = "http://example.com/mainserver", className = "com.example.client.CancelMovieTickets")
    @ResponseWrapper(localName = "cancelMovieTicketsResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.CancelMovieTicketsResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/cancelMovieTicketsRequest", output = "http://example.com/mainserver/MainServerImpl/cancelMovieTicketsResponse")
    public String cancelMovieTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingSchedule", targetNamespace = "http://example.com/mainserver", className = "com.example.client.GetBookingSchedule")
    @ResponseWrapper(localName = "getBookingScheduleResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.GetBookingScheduleResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/getBookingScheduleRequest", output = "http://example.com/mainserver/MainServerImpl/getBookingScheduleResponse")
    public String getBookingSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exchangeTickets", targetNamespace = "http://example.com/mainserver", className = "com.example.client.ExchangeTickets")
    @ResponseWrapper(localName = "exchangeTicketsResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.ExchangeTicketsResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/exchangeTicketsRequest", output = "http://example.com/mainserver/MainServerImpl/exchangeTicketsResponse")
    public String exchangeTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovieSlots", targetNamespace = "http://example.com/mainserver", className = "com.example.client.AddMovieSlots")
    @ResponseWrapper(localName = "addMovieSlotsResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.AddMovieSlotsResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/addMovieSlotsRequest", output = "http://example.com/mainserver/MainServerImpl/addMovieSlotsResponse")
    public String addMovieSlots(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookMovieTickets", targetNamespace = "http://example.com/mainserver", className = "com.example.client.BookMovieTickets")
    @ResponseWrapper(localName = "bookMovieTicketsResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.BookMovieTicketsResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/bookMovieTicketsRequest", output = "http://example.com/mainserver/MainServerImpl/bookMovieTicketsResponse")
    public String bookMovieTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMovieShowsAvailability", targetNamespace = "http://example.com/mainserver", className = "com.example.client.ListMovieShowsAvailability")
    @ResponseWrapper(localName = "listMovieShowsAvailabilityResponse", targetNamespace = "http://example.com/mainserver", className = "com.example.client.ListMovieShowsAvailabilityResponse")
    @Action(input = "http://example.com/mainserver/MainServerImpl/listMovieShowsAvailabilityRequest", output = "http://example.com/mainserver/MainServerImpl/listMovieShowsAvailabilityResponse")
    public String listMovieShowsAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
