
package com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MainServerImplService", targetNamespace = "http://example.com/mainserver", wsdlLocation = "http://localhost:8080/mainserver?wsdl")
public class MainServerImplService
    extends Service
{

    private final static URL MAINSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAINSERVERIMPLSERVICE_EXCEPTION;
    private final static QName MAINSERVERIMPLSERVICE_QNAME = new QName("http://example.com/mainserver", "MainServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mainserver?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAINSERVERIMPLSERVICE_WSDL_LOCATION = url;
        MAINSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public MainServerImplService() {
        super(__getWsdlLocation(), MAINSERVERIMPLSERVICE_QNAME);
    }

    public MainServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAINSERVERIMPLSERVICE_QNAME, features);
    }

    public MainServerImplService(URL wsdlLocation) {
        super(wsdlLocation, MAINSERVERIMPLSERVICE_QNAME);
    }

    public MainServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAINSERVERIMPLSERVICE_QNAME, features);
    }

    public MainServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MainServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MainServerImpl
     */
    @WebEndpoint(name = "MainServerImplPort")
    public MainServerImpl getMainServerImplPort() {
        return super.getPort(new QName("http://example.com/mainserver", "MainServerImplPort"), MainServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MainServerImpl
     */
    @WebEndpoint(name = "MainServerImplPort")
    public MainServerImpl getMainServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/mainserver", "MainServerImplPort"), MainServerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAINSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw MAINSERVERIMPLSERVICE_EXCEPTION;
        }
        return MAINSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
