
package Replicas.FaraazBackup.com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OUTImplService", targetNamespace = "http://example.com/out", wsdlLocation = "http://localhost:8087/out?wsdl")
public class OUTImplService
    extends Service
{

    private final static URL OUTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OUTIMPLSERVICE_EXCEPTION;
    private final static QName OUTIMPLSERVICE_QNAME = new QName("http://example.com/out", "OUTImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/out?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OUTIMPLSERVICE_WSDL_LOCATION = url;
        OUTIMPLSERVICE_EXCEPTION = e;
    }

    public OUTImplService() {
        super(__getWsdlLocation(), OUTIMPLSERVICE_QNAME);
    }

    public OUTImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OUTIMPLSERVICE_QNAME, features);
    }

    public OUTImplService(URL wsdlLocation) {
        super(wsdlLocation, OUTIMPLSERVICE_QNAME);
    }

    public OUTImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OUTIMPLSERVICE_QNAME, features);
    }

    public OUTImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OUTImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OUTImpl
     */
    @WebEndpoint(name = "OUTImplPort")
    public OUTImpl getOUTImplPort() {
        return super.getPort(new QName("http://example.com/out", "OUTImplPort"), OUTImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OUTImpl
     */
    @WebEndpoint(name = "OUTImplPort")
    public OUTImpl getOUTImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/out", "OUTImplPort"), OUTImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OUTIMPLSERVICE_EXCEPTION!= null) {
            throw OUTIMPLSERVICE_EXCEPTION;
        }
        return OUTIMPLSERVICE_WSDL_LOCATION;
    }

}
