
package Replicas.FaraazBackup.com.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OUTImpl", targetNamespace = "http://example.com/out")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OUTImpl {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "logOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.LogOUT")
    @ResponseWrapper(localName = "logOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.LogOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/logOUTRequest", output = "http://example.com/out/OUTImpl/logOUTResponse")
    public void logOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovieSlotsOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.AddMovieSlotsOUT")
    @ResponseWrapper(localName = "addMovieSlotsOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.AddMovieSlotsOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/addMovieSlotsOUTRequest", output = "http://example.com/out/OUTImpl/addMovieSlotsOUTResponse")
    public String addMovieSlotsOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeMovieSlotsOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.RemoveMovieSlotsOUT")
    @ResponseWrapper(localName = "removeMovieSlotsOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.RemoveMovieSlotsOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/removeMovieSlotsOUTRequest", output = "http://example.com/out/OUTImpl/removeMovieSlotsOUTResponse")
    public String removeMovieSlotsOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelMovieTicketsOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.CancelMovieTicketsOUT")
    @ResponseWrapper(localName = "cancelMovieTicketsOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.CancelMovieTicketsOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/cancelMovieTicketsOUTRequest", output = "http://example.com/out/OUTImpl/cancelMovieTicketsOUTResponse")
    public String cancelMovieTicketsOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingScheduleOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.GetBookingScheduleOUT")
    @ResponseWrapper(localName = "getBookingScheduleOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.GetBookingScheduleOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/getBookingScheduleOUTRequest", output = "http://example.com/out/OUTImpl/getBookingScheduleOUTResponse")
    public String getBookingScheduleOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookMovieTicketsOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.BookMovieTicketsOUT")
    @ResponseWrapper(localName = "bookMovieTicketsOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.BookMovieTicketsOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/bookMovieTicketsOUTRequest", output = "http://example.com/out/OUTImpl/bookMovieTicketsOUTResponse")
    public String bookMovieTicketsOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMovieShowsAvailabilityOUT", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.ListMovieShowsAvailabilityOUT")
    @ResponseWrapper(localName = "listMovieShowsAvailabilityOUTResponse", targetNamespace = "http://example.com/out", className = "Replicas.FaraazBackup.com.example.client.ListMovieShowsAvailabilityOUTResponse")
    @Action(input = "http://example.com/out/OUTImpl/listMovieShowsAvailabilityOUTRequest", output = "http://example.com/out/OUTImpl/listMovieShowsAvailabilityOUTResponse")
    public String listMovieShowsAvailabilityOUT(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
